# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'abc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for abc
pod 'Cosmos', '~> 23.0'
pod 'Alamofire'

  target 'abcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'abcUITests' do
    # Pods for testing
  end

end
