# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlowerVala' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'IQKeyboardManager'
  # Pods for FlowerVala

  target 'FlowerValaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlowerValaUITests' do
    # Pods for testing
  end

end
