# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Buyer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'DPOTPView'
pod 'AEOTPTextField'
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'OTPFieldView'
pod 'FirebaseFirestore'
pod 'Firebase'
  # Pods for Buyer

  target 'BuyerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuyerUITests' do
    # Pods for testing
  end

end
