# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurdVala' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'IQKeyboardManagerSwift’


  # Pods for CurdVala

  target 'CurdValaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurdValaUITests' do
    # Pods for testing
  end

end
